baseURL = "http://hugo-cicd-herrera.s3-website.us-east-2.amazonaws.com/"
languageCode = 'en-us'
title = "Hugo AWS CD"
theme = "ananke"
[[deployment.targets]]
# An arbitrary name for this target
name = "awsbucket"
URL = "s3://hugo-cicd-herrera/?region=us-east-2"